Practice JavaScript 1
DSTU-frontend-practice-2021/Group-3 pull request #17
Opened 2021-06-29 06:40 UTC by OleinikConst

Tasks 1-i.js, 1-ii.js,  1-iii.js

2021-06-29 21:33 UTC, iamresp requested changes

2021-06-29 21:33 UTC, iamresp commented on solutions/1-i.js
> +    if (month <= 3) {
Очень популярное решение :)
Если вкратце — стоит попробовать решить без условий. Ссылка на более подробный комментарий к аналогичному решению этой задачи, чтобы не повторяться: https://github.com/DSTU-frontend-practice-2021/Group-2/pull/9#discussion_r660956505

2021-06-29 21:33 UTC, iamresp commented on solutions/1-iii.js
> +    if (health <= 0) {
Можно решить без условия, что называется, в одну строчку: операции сравнения всегда возвращают булево значение.

2021-07-02 00:19 UTC, ankormoreankor commented on solutions/1-iii.js
> +    if (health <= 0) {
Можно, но это задание для новичка на внимательность)

2021-07-02 00:21 UTC, ankormoreankor commented on solutions/1-ii.js
> +    return [humanYears, (humanYears - 2) * 4 + 24, (humanYears - 2) * 5 + 24]
По вашей формуле если humanYears === 2, получим [2, 24, 24], стало быть условие выше - лишнее.

2021-07-02 00:21 UTC, merged